[build]
  base = "/"
  publish = "public"
  command = "npm install"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"